name: Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: pnpm/action-setup@v4
        with:
          version: 9
      -
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: pnpm install
      -
        name: Build
        run: pnpm run build
      -
        name: Deploy with rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      -
        run: 'rclone copy dist derpus:derpus/greystar'